# Generated by Django 2.2.5 on 2021-04-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='oxy_sup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=2000)),
                ('City', models.CharField(max_length=2000)),
                ('Contact', models.CharField(max_length=2000)),
                ('Number', models.CharField(max_length=20000)),
            ],
        ),
    ]
