# Generated by Django 2.2.5 on 2021-04-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hosp_city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=2000)),
                ('state_code', models.CharField(max_length=20)),
                ('pointer', models.CharField(max_length=2000)),
            ],
        ),
    ]
