# Generated by Django 2.2.5 on 2021-04-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='med_serv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2000)),
                ('state_code', models.CharField(max_length=10)),
                ('dist_name', models.CharField(max_length=2000)),
                ('address', models.CharField(max_length=20000)),
                ('email', models.CharField(max_length=2000)),
                ('telephone', models.CharField(max_length=200)),
            ],
        ),
    ]
