# Generated by Django 2.2.5 on 2021-04-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='med_serv',
            name='telephone',
            field=models.CharField(max_length=2000),
        ),
    ]
