# Generated by Django 2.2.5 on 2021-04-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food_ser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Area', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('Number', models.CharField(max_length=200)),
                ('Hours', models.CharField(max_length=200)),
                ('Service', models.CharField(max_length=200)),
                ('Social', models.CharField(max_length=200)),
                ('Delivery', models.CharField(max_length=200)),
            ],
        ),
    ]
