# Generated by Django 2.2.5 on 2021-04-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerOB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('state_code', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('services_offered', models.CharField(max_length=20000)),
            ],
        ),
    ]
