# Generated by Django 2.2.5 on 2021-04-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_ob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerob',
            name='blood_type',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerob',
            name='plasma_donor',
            field=models.CharField(default='n', max_length=200),
            preserve_default=False,
        ),
    ]
